### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by ookla-ariel-ride** [nicjansma/plex-poster-optimizer#4]
I have a large library, I can run this successfully using max 10000.  Anything beyond 10000 and I get the following error:

Finding better 567 posters!
(node:29930) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at /home/plexguide/plex-poster-optimizer/index.js:250:47
    at /home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:3110:16
    at replenish (/home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:1011:17)
    at /home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:1046:16)
    at /home/plexguide/plex-poster-optimizer/index.js:249:15
    at nextTask (/home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:5324:14)
    at next (/home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:5331:9)
    at /home/plexguide/plex-poster-optimizer/node_modules/async/dist/async.js:969:16
(node:29930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nicjansma** [comment]
Fixed with https://github.com/nicjansma/plex-poster-optimizer/commit/2aba1cb38350e520f8450fa535b224c38d836231, let me know if there's anything else!
